/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "DATA_TYPE.h"
#include "STM32f103XX.h"
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

u8 NVIC_u8EnableInterrupt(u8 copy_u8IRQ)
{

	u8 x,y;
	x= copy_u8IRQ /32;
	y =copy_u8IRQ-32*x;
	NVIC->ISER[x]= (1<<y);
}

u8 NVIC_u8u8Setpending(u8 copy_u8IRQ)
{
	u8 x,y;
	x= copy_u8IRQ /32;
	y =copy_u8IRQ -32 *x;
	NVIC->ISPR[x]= (1<<y);
}
void EXTI0_IRQHandler(void)
{
	int d=1;

}

int main(void)
{
	NVIC_u8EnableInterrupt(6);
	NVIC_u8u8Setpending(6);
    /* Loop forever */
	for(;;);
}
