/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "DATA_TYPE.h"
#include "STM32f103XX.h"

#include "NVIC_interface.h"
#include "CLK_interface.h"
#include "DMA_interface.h"


int main(void)
{
	u32 x[1000] ={0};
	u32 y[1000];
	Channel_Config pstr = {Channel_Num1,Memory_To_Memory_EN,MEDIUM,BYTE4,BYTE4_PR,MEMORY_INC_EN,PERIPHERAL_INC_EN,CIRCULAR_DE,MEMORY,TEI_DE,HTI_DE,CTI_DE,Channel_EN};


	RCC_u8EnPripheral(DMA1_U8_CLK);

	DMA_voidChannelStart(0,y,x,999);
	DMA_voidInit(&pstr);
	for(;;);
}
