/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
/*void chang_unprivalig(void);

void acc_priv(void)
{
	int *x=(int* 0x)
}
void HardFault_Handler (void)
{
	while(1);
}*/
#include <stdint.h>
#include "DATA_TYPE.h"
//#include "CLK_interface.h"
//#include "CLK_private.h"
#define  BASE_ADDRESS_GPIO    (0x40011004UL)
int main(void)
{



	//chang_unprivalig();

	int val =60 ;
	int val2 =100;
    int *p =(int *)0x20004000;
    int x=10;
    *p =200;


	__asm volatile("MOV  R0,%0"::"r"(val));
	__asm volatile("MOV  R2,%0"::"r"(val2));
	__asm volatile("MOV  %0,R0":"=r"(val2):);
	__asm volatile("MOV  %0,R2":"=r"(val):);


	__asm volatile("MOV R1,%0"::"r"(p));
	__asm volatile("LDR R5,[R1]");
	__asm volatile("MOV %0,R5":"=r"(x):);

	//__asm volatile ("MRS  %0, CONTROL":"=r"(val):);
	/*save meomery location into gprs reg */
	//__asm volatile("LDR R0,=#0x20001000");
	//__asm volatile("LDR R1,=#0x20001004");

	/*reed the values */
//	__asm volatile("LDR R2,[R0]");

	//__asm volatile("LDR R3,[R1]");

	/*add two values */

	//__asm volatile("ADD R4,R2,#5");

	/*write the value back  */

	//__asm volatile("STR R4, [R0]");

/*	u32 *reg_gpioc =(u32*)BASE_ADDRESS_GPIO;

	RCC_voidInit();
	RCC_u8EnPripheral(GPIO_U8_PORTC_CLK_EN);

	*reg_gpioc|=(1<<20);
*/
	for(;;);
}



/*
void chang_unprivalig(void)
{
    __asm volatile("MRS R0,CONTROL");
	__asm volatile("ORR R0,#1");
   __asm volatile("MSR CONTROL,R0");
	//__asm volatile("MSR CONTROL,R0");

}
*/
