/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "DATA_TYPE.h"
#define  BASE_ADDRESS_ADC     (0x40012400UL)
#define  OFFSIT_ADDRES_ADC    (0x04UL)
#define  ADC_REG              (OFFSIT_ADDRES_ADC+BASE_ADDRESS_ADC)


#define  BASE_ADDRESS_RCC     (0x40021000UL)
#define  OFFSIT_ADDRES_RCC    (0x18UL)
#define  RCC_REG              (OFFSIT_ADDRES_RCC+BASE_ADDRESS_RCC)


#define  BASE_ADDRESS_GPIO    (0x40011004UL)



int main(void)
{
	u32 *reg_rcc =   (u32*)RCC_REG;
	u32 *reg_adc =   (u32*)ADC_REG;
	u32 *reg_gpioc =(u32*)BASE_ADDRESS_GPIO;



	*reg_rcc |=(1<<4);
	*reg_adc |=(1<<8);
	*reg_gpioc|=(1<<20);

    /* Loop forever */
	for(;;);
}
