/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "DATA_TYPE.h"
#include "STM32f103XX.h"

#include "CLK_interface.h"
#include "GPIO_interface.h"

#define SYST_CSR  *((volatile u32*)(0xE000E010))
#define SYST_RVR  *((volatile u32*)(0xE000E014))
#define SYST_CVR *((volatile u32*)(0xE000E018))
#define SYST_CALIB  *((volatile u32*)(0xE000E01C))

void sys_tictime(u32 val)
{
	SYST_RVR  = val;
	SYST_CSR |=3;

}

void SysTick_Handler(void)
{
		GPIO_u8TogPin(GPIOC_U8_PORT,GPIO_U8_PIN13);
}

/*
typedef struct
{
	u8 copy_u8port;
	u8 copy_u8pinNum;
	u8 copy_PinMode;

}PIN_CINFIG;
*/
int main(void)
{
	int x=0;

	PIN_CINFIG Pstr ={GPIOC_U8_PORT,GPIO_U8_PIN13,GPIO_U8_OUTPUT_PUSH_PULL_10MHZ};

	sys_tictime(300000);

	RCC_u8EnPripheral(GPIO_U8_PORTC_CLK);

	GPIO_voidInit(&Pstr);

	for(;;);


    /* Loop forever */
}

