/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "DATA_TYPE.h"
#include "STM32f103XX.h"
#include "NVIC_interface.h"
#include <stdint.h>


int main(void)
{
	SCB_u8InitPriortyField(BIT2_SUB_2BIT_GROUP);

	NVIC_u8Setpriorty(35,  GROUP_U8_PRIORITY_TWO  ,SUB_U8_PRIORITY_ONE);

	NVIC_u8Setpriorty(6, GROUP_U8_PRIORITY_TWO  ,SUB_U8_PRIORITY_THREE);

	NVIC_u8EnableInterrupt(6);

	NVIC_u8EnableInterrupt(35);

	NVIC_u8u8Setpending(6);

	for(;;);
}

/* IRQ = 6 */
void EXTI0_IRQHandler(void)
{
	NVIC_u8u8Setpending(35);
    while(1);
}

/* IRQ = 35 */
void SPI1_IRQHandler(void)
{

` while(1);
}
