/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "DATA_TYPE.h"
#include "STM32f103XX.h"
#include "EXTI_interface.h"
#include "NVIC_interface.h"
#include "GPIO_interface.h"
#include "CLK_interface.h"
void tog(void);
int main(void)
{
   RCC_u8EnPripheral(GPIO_U8_PORTA_CLK);

   RCC_u8EnPripheral(GPIO_U8_PORTC_CLK);

   RCC_u8EnPripheral(ALT_FUN_U8_IO_CLK);

   EXTI_voidCallBackFunEXTI0(&tog);



   PIN_CINFIG pin = {GPIOA_U8_PORT,GPIO_U8_PIN0,GPIO_U8_INPUT_PULLDOWN};

   PIN_CINFIG pin1 = {GPIOC_U8_PORT,GPIO_U8_PIN13,GPIO_U8_OUTPUT_PUSH_PULL_10MHZ};

   EXT_PIN_CONFIG  pinx={PORTA,PIN0};

   GPIO_voidInit(&pin);
   GPIO_voidInit(&pin1);
   GPIO_u8SetPinValue(GPIOC_U8_PORT,GPIO_U8_PIN13,GPIO_U8_LOW);
   NVIC_u8EnableInterrupt(6);
   EXTI_u8Init(&pinx);
   EXTI_u8Enable(EXTI0_U8_PRIF,EN_RISING_TRIGGER);

	for(;;);
}

void tog(void)
{
  GPIO_u8TogPin(GPIOC_U8_PORT, GPIO_U8_PIN13);
}
